group 'com.webcare.zoom'
version '1.5.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.aliyun.com/repository/jcenter" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'org.jetbrains.compose:compose-gradle-plugin:1.7.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.23'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.aliyun.com/repository/jcenter" }

        flatDir {
            dirs project(':zoom').file('libs')
        }
    }
}

apply plugin: 'com.android.library'
apply from: 'libs/versions.gradle'

android {
    namespace 'com.webcare.zoom'
    compileSdkVersion 36
    buildToolsVersion = "36.0.0"

    viewBinding {
        enabled = true
    }

    defaultConfig {
        minSdkVersion 28
        targetSdkVersion 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        consumerProguardFiles 'proguard.cfg'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Updates for 6.6.9
    implementation libraries.nimbusds
    implementation libraries.browser
    implementation libraries.androidxCoreKtx
    implementation libraries.jetbrainskotlin

    // ExoPlayer - Required by mobilertc.aar
    implementation libraries.exoplayerCore
    implementation libraries.exoplayerUI

    // Lottie - Required by mobilertc.aar for animations
    implementation libraries.lottie

    // Additional mobilertc.aar dependencies
    implementation libraries.glideAnnotations
    implementation libraries.glideGlide
    implementation libraries.windowJava
    implementation libraries.scaleImageView
    implementation libraries.splashScreenLib
    implementation libraries.workerManager
    implementation libraries.androidxWebkitKtx
    implementation libraries.coil
    implementation libraries.coilGif
    implementation libraries.composeConstraintlayout

    implementation libraries.supportAnnotation
    implementation libraries.kotlinStdlibJdk
    implementation libraries.kotlinStdlibJdk7
    implementation libraries.constraintlayout
    implementation libraries.recyclerview
    implementation libraries.kotlinxCoroutinesCore
    implementation libraries.androidxCore
    implementation libraries.kotlinStdlibCommon
    implementation libraries.fragmentx
    implementation libraries.fragmentKtx
    implementation libraries.viewBindingX
    implementation libraries.supportAppcompat
    implementation libraries.okio
    implementation libraries.collection
    implementation libraries.annotationExperimental
    implementation libraries.kotlinxCoroutinesAndroid
    implementation libraries.collectionKtx
    implementation libraries.viewmodel
    implementation libraries.activityx
    implementation libraries.lifecycleKtx
    implementation libraries.viewmodelKtx
    implementation libraries.lifecycleCommon
    implementation libraries.lifecycleCommonJava
    implementation libraries.livedataCore
    implementation libraries.lifecycle
    implementation libraries.livedata
    implementation libraries.livedataKtx
    implementation libraries.livedataCoreKtx
    implementation libraries.lifecycleViewModelSavedState
    implementation libraries.listenablefuture
    implementation libraries.archCoreCommon
    implementation libraries.archCoreRuntime
    implementation libraries.swiperefreshlayout
    implementation libraries.coordinatorlayout
    implementation libraries.vectordrawable
    implementation libraries.vectordrawableAnimated
    implementation libraries.firebaseAnnotation
    implementation libraries.playServiceFido
    implementation libraries.playServiceBasement
    implementation libraries.playServiceTask
    implementation libraries.constraintlayoutCore
    implementation libraries.gson
    // Use protobuf-javalite for Android (protobuf-java causes duplicate classes)
    // implementation libraries.protobufJava
    implementation libraries.protobufJavalite
    implementation libraries.errorProneAnnotations
    implementation libraries.guava
    implementation libraries.activityKtx
    implementation libraries.drawerlayout
    implementation libraries.customview
    implementation libraries.startup
    // APM libraries are not publicly available (JCenter/Bintray shutdown)
    // implementation libraries.apmCommon
    // implementation libraries.apmApis
    implementation libraries.lifecycleService
    implementation libraries.javapoet

    //compose start
    implementation libraries.composeMaterial3

    implementation libraries.composeMaterial
    implementation libraries.composeActivity
    implementation libraries.composeAnimation
    implementation libraries.composeAnimationCore
    implementation libraries.composeNavigation
    implementation libraries.composeFoundation
    implementation libraries.composeFoundationLayout
    implementation libraries.composeRuntime
    implementation libraries.composeRuntimeSaveable
    implementation libraries.composeLifecycle
    implementation libraries.composeLifecycleViewmodel
    implementation libraries.composeUI
    implementation libraries.composeUIGeometry
    implementation libraries.composeUIGraphics
    implementation libraries.composeUIText
    implementation libraries.composeUIUnit
    implementation libraries.composeUIUtil
    implementation libraries.composeUITest
    implementation libraries.composeUITooling
    implementation libraries.composeUIToolingPreview
    //----compose related----//
    implementation libraries.emoji2
    implementation libraries.emoji2ViewsHelper
    implementation libraries.exifinterface
    implementation libraries.lifecycleProcess
    implementation libraries.concurrentFutures
    implementation libraries.savedstate
    implementation libraries.savedstateKtx
    implementation libraries.media
    implementation libraries.playServicesBase
    implementation libraries.supportWindow
    implementation libraries.kotlinxCoroutinesSwing
    implementation libraries.kotlinxCoroutinesCoreJvm
    implementation libraries.jetbrainsAnnotations
    implementation libraries.kotlinParcelize
    implementation libraries.profileinstaller
    //compose end

    // Start - CameraX and MLKit text-recognition
    implementation libraries.dataTransportApi
    implementation libraries.dataTrasnsportBackendCct
    implementation libraries.dataTrasnsportRuntime
    implementation libraries.firebaseComponenets
    implementation libraries.firebaseEncoders
    implementation libraries.firebaseEncodersJson
    implementation libraries.androidxTracing


    implementation libraries.rxAndroid
    implementation libraries.reactiveStream
    implementation libraries.okhttp
    implementation libraries.kotlinxAtomicfu

    implementation libraries.mlkitCommon
    implementation libraries.composeMaterialRipple
    implementation libraries.coilGif

    api(name: 'mobilertc', ext: 'aar')
}

